name: Auto Update Naukri Profile

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # 08:00 AM IST
    - cron: '0 3 * * *'  # 09:00 AM IST
    - cron: '0 4 * * *'  # 10:00 AM IST
    - cron: '0 5 * * *'  # 11:00 AM IST
    - cron: '0 6 * * *'  # 12:00 PM IST

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies and Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps

      - name: Run Naukri Automation Script
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASS: ${{ secrets.NAUKRI_PASS }}
        run: python naukri_update.py

      - name: Upload screenshots if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: |
            after_login.png

      - name: Send Slack Notification
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "✅ Naukri profile login successful for Mohammed Ikram Khan!"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
